[github_app]
pr_commands = [
    "/review",
    "/improve --pr_code_suggestions.commitable_code_suggestions=true",
]

[pr_reviewer]
enable_review_labels_effort = true

[best_practices]
enable_global_best_practices = true
organization_name="Digital Wisdom"
